// #region Drivers
GET http://localhost:3010/drivers

###
GET http://localhost:3010/drivers?filter=age&value=25

###
GET http://localhost:3010/drivers?filter=driver_license

###
GET http://localhost:3010/drivers?value=2

###
POST http://localhost:3010/drivers
Content-Type: application/json

{
    "age": 20,
    "first_name": "name",
    "last_name": "last",
    "driver_license": "asdfasdf asdf asd"
}

// #endregion
###
// #region Vehicles
GET http://localhost:3010/drivers/5e6021d5e9efaa24d0762f19/vehicles

###
GET http://localhost:3010/drivers/5e6021d5e9efaa24d0762f19/vehicles/5e60213b54a61a49488354fd

// #endregion